---

- name: Link /opt/apigee to {{ apigee_edge_installation_path }}
  file:
    path: /opt/apigee
    state: link
    src: '{{ apigee_edge_installation_path }}'
    owner: apigee
    group: apigee
  when: apigee_edge_installation_path != "/opt/apigee"
