
- name: Set Cassandra limits
  copy:
    src: 99-cassandra.conf
    dest: /etc/security/limits.d/99-cassandra.conf
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups['dsdr']

- name: Set Message Processor limits
  copy:
    src: 99-message-processor.conf
    dest: /etc/security/limits.d/99-message-processor.conf
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups['mpdr']

